# NLP: Delivery 2, Train Models

## Lily Voge, Jan Urankar, Luka Markicevic, Nikolaos Athanasopoulos, Zoltan Kunos

## Named Entity Recognition

The objective of this project is to fully understand the structured perceptron algorithm
applied to Named Entity Recognition (NER). NER problems are very useful in many
contexts, from information retrieval to question answering systems. The goal of this project
is not to achieve the best results, but to fully understand all the details about a simple
solution.


### Import Libraries

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

#Vector operations and data management
import pandas as pd
import scipy
import numpy as np

#Importing custom functions
import utils

#Folder management
import os,sys,inspect

#Model and other data type saving
import pickle

#Printing styling
import pprint
from IPython.display import display, HTML

#Plot management
import seaborn as sns
import matplotlib.pyplot as plt

#Skseq
import skseq
from skseq.sequences import sequence
from skseq.sequences.sequence import Sequence
from skseq.sequences.sequence_list import SequenceList
from skseq.sequences.label_dictionary import LabelDictionary
import skseq.sequences.structured_perceptron as spc
from skseq.sequences import extended_feature

#Metrics
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import utils.utils as utils

import dill

In [2]:
def save(name,file):
    with open(name, "wb") as f:
        pickle.dump(file, f)
def load(name):
    with open(name, 'rb') as f:
        return(pickle.load(f))

In [3]:
train = pd.read_csv("data/train_data_ner.csv")
test = pd.read_csv("data/test_data_ner.csv")
TINY_TEST,y_true_tiny = utils.get_tiny_test()

In [4]:
train.head()

sentence_id          words tags
0            0      Thousands    O
1            0             of    O
2            0  demonstrators    O
3            0           have    O
4            0        marched    O


# Train/Test set up <a id='train/test'></a>



In [5]:
X_train = train['words']
y_train = train['tags']
X_test = test['words']
y_test = test['tags']

In [6]:
#Train vectors (list of lists)
X_train = [] #Contains the sentences (words)
y_train = [] #Contains the tags (aka target)

#The column "sentence_id" does not follow a cardinal order so we group all the unique id's for later iteration
valid_ids_train = train.sentence_id.unique()

for sentence in valid_ids_train:
    X_train.append(list(train[train["sentence_id"]==sentence]["words"].values))
    y_train.append(list(train[train["sentence_id"]==sentence]["tags"].values))

In [7]:
#Train vectors (list of lists)
X_test = [] #Contains the sentences (words)
y_test = [] #Contains the tags (aka target)

#The column "sentence_id" does not follow a cardinal order so we group all the unique id's for later iteration
valid_ids_test = test.sentence_id.unique()

for sentence in valid_ids_test:
    X_test.append(list(test[test["sentence_id"]==sentence]["words"].values))
    y_test.append(list(test[test["sentence_id"]==sentence]["tags"].values))

In [8]:
#Example of a train & test set sentence/tags combination
i = 1000

for X_word, y_tag in zip(X_train[i],y_train[i]):
    print(X_word+"/"+y_tag,end=" ")
print("\n")
for X_word, y_tag in zip(X_test[i],y_test[i]):
    print(X_word+"/"+y_tag,end=" ")

Naqib/B-per and/O some/O of/O his/O family/O members/O and/O guards/O were/O wounded/O in/O the/O blast/O and/O at/O least/O two/O others/O were/O killed/O ./O 

President/B-per Chavez/I-per is/O on/O a/O two-day/B-tim visit/O to/O Russia/B-geo ./O 

# Corpus Creation <a id=corpus></a>

This is a function that creates two dictionaries as follows:

* word_pos: stores every unique word (key) of the training set in a unique value

* tag_pos: stores every unique tag (key) of the training set in a unique value

In [9]:
corpus_word_dict, corpus_tag_dict = utils.corpus(X_train, y_train)

In [10]:
corpus_tag_dict

{'O': 0,
 'B-geo': 1,
 'B-gpe': 2,
 'B-tim': 3,
 'B-org': 4,
 'I-geo': 5,
 'B-per': 6,
 'I-per': 7,
 'I-org': 8,
 'B-art': 9,
 'I-art': 10,
 'I-tim': 11,
 'I-gpe': 12,
 'B-nat': 13,
 'I-nat': 14,
 'B-eve': 15,
 'I-eve': 16}

# Training sequence creation

Creating the sequence list from the training corpus. 

In [13]:
train_seq = SequenceList(LabelDictionary(corpus_word_dict), LabelDictionary(corpus_tag_dict))
for word,tag in zip(X_train,y_train):
    train_seq.add_seq_cython(word,tag, LabelDictionary(corpus_word_dict), LabelDictionary(corpus_tag_dict))

In [14]:
print(train_seq.__dict__.keys())
print(type(train_seq))

dict_keys(['x_dict', 'y_dict', 'seq_list'])
<class 'skseq.sequences.sequence_list.SequenceList'>


In [39]:
# Saving the sequence

# Create the directory "fitted models" if it doesn't already exist
if not os.path.exists("fitted_models"):
    os.makedirs("fitted_models")
    
# Check if the file exists
if os.path.exists("./fitted_models/train_seq.dill"):
    # Delete the file
    os.remove("./fitted_models/train_seq.dill")

# Save the train_seq object to disk
with open('fitted_models/train_seq.dill', 'wb') as f:
    dill.dump(train_seq, f)

In [17]:
print(train_seq[1000],"\n")
print(train_seq[1000].to_words(sequence_list = train_seq))

4715/6 13/0 365/0 1/0 188/0 1308/0 429/0 13/0 4324/0 431/0 1932/0 11/0 9/0 122/0 13/0 140/0 1153/0 468/0 163/0 431/0 159/0 21/0  

Naqib/B-per and/O some/O of/O his/O family/O members/O and/O guards/O were/O wounded/O in/O the/O blast/O and/O at/O least/O two/O others/O were/O killed/O ./O 


# Structured Perceptron Model training using default features

Creating the feature mapper using only the given default features.

In [18]:
feature_mapper = skseq.sequences.id_feature.IDFeatures(train_seq)
# get features
feature_mapper.build_features()
pprint.pprint(list(feature_mapper.__dict__.keys()))

['feature_dict',
 'feature_list',
 'add_features',
 'dataset',
 'node_feature_cache',
 'initial_state_feature_cache',
 'final_state_feature_cache',
 'edge_feature_cache']


In [19]:
list(feature_mapper.feature_dict)[0:10]

['init_tag:O',
 'id:Thousands::O',
 'id:of::O',
 'prev_tag:O::O',
 'id:demonstrators::O',
 'id:have::O',
 'id:marched::O',
 'id:through::O',
 'id:London::B-geo',
 'prev_tag:O::B-geo']

In [20]:
id_seq = 1

print ("Initial features:",     feature_mapper.feature_list[id_seq][0])
print ("Transition features:",  feature_mapper.feature_list[id_seq][1])
print ("Final features:",       feature_mapper.feature_list[id_seq][2])
print ("Emission features:",    feature_mapper.feature_list[id_seq][3])

Initial features: [[0]]
Transition features: [[3], [32], [34], [3], [3], [3], [3], [9], [11], [3], [3], [3], [3], [44], [46], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [9], [58], [59]]
Final features: [[28]]
Emission features: [[29], [30], [31], [33], [35], [36], [15], [13], [37], [38], [39], [40], [41], [42], [43], [45], [47], [48], [10], [5], [49], [10], [50], [51], [52], [53], [54], [15], [55], [56], [57], [27]]


Perceptron creation using our dictionary of words, tags and the feature mapper

In [21]:
sp = spc.StructuredPerceptron(corpus_word_dict, corpus_tag_dict, feature_mapper)
sp.num_epochs = 5

In [22]:
sp.get_num_states(), sp.get_num_observations()

(17, 31979)

In [23]:
%%time
num_epochs = 15
sp.fit(feature_mapper.dataset, num_epochs)

Epoch: 0 Accuracy: 0.893815
Epoch: 1 Accuracy: 0.931674
Epoch: 2 Accuracy: 0.940913
Epoch: 3 Accuracy: 0.946175
Epoch: 4 Accuracy: 0.950018
Epoch: 5 Accuracy: 0.952577
Epoch: 6 Accuracy: 0.954425
Epoch: 7 Accuracy: 0.956033
Epoch: 8 Accuracy: 0.957185
Epoch: 9 Accuracy: 0.958481
Epoch: 10 Accuracy: 0.959217
Epoch: 11 Accuracy: 0.960524
Epoch: 12 Accuracy: 0.961121
Epoch: 13 Accuracy: 0.961207
Epoch: 14 Accuracy: 0.961983
CPU times: user 30min 41s, sys: 6.34 s, total: 30min 48s
Wall time: 30min 45s


In [24]:
# Model saving

sp.save_model("fitted_models/01_Default_Features")

In [25]:
#Model loading
sp_default = spc.StructuredPerceptron(corpus_word_dict, corpus_tag_dict, feature_mapper)
sp_default.load_model(dir="fitted_models/01_Default_Features")
sp_default.parameters

array([ 8.6     ,  8.6     , 12.666667, ..., -2.666667,  1.866667,
        0.      ])

In [26]:
sp.parameters

array([ 8.6       ,  8.6       , 12.66666667, ..., -2.66666667,
        1.86666667,  0.        ])

# Structured Perceptron Model Training using added, personalized features

In [27]:
added_feature_mapper = skseq.sequences.extended_feature.ExtendedFeatures(train_seq) 
# get features
added_feature_mapper.build_features()
pprint.pprint(list(added_feature_mapper.__dict__.keys()))

['feature_dict',
 'feature_list',
 'add_features',
 'dataset',
 'node_feature_cache',
 'initial_state_feature_cache',
 'final_state_feature_cache',
 'edge_feature_cache']


We group the new features in the following categories:

In [28]:
added = ["capi","point","ending","prep"]

In [29]:
for index,feat_type in enumerate(added):
    print(str(index)+". "+feat_type,end="\n")
    print([feature for feature in list(added_feature_mapper.feature_dict.keys()) if feat_type in feature],end="\n\n")

0. capi
['capi_ini::O', 'capi_ini::B-geo', 'capi_ini::B-gpe', 'capi_ini::B-tim', 'capi_ini::B-org', 'capi_ini::I-geo', 'capi_any::B-geo', 'capi_ini::B-per', 'capi_ini::I-per', 'capi_any::O', 'capi_ini::I-org', 'capi_ini::B-art', 'capi_any::B-art', 'capi_ini::I-art', 'id:capital::O', 'capi_any::B-org', 'capi_any::I-tim', 'capi_any::I-org', 'capi_any::B-tim', 'capi_ini::I-tim', 'id:capita::O', 'capi_any::B-per', 'capi_ini::I-gpe', 'capi_any::B-gpe', 'capi_any::I-per', 'capi_ini::B-nat', 'capi_ini::I-nat', 'capi_ini::B-eve', 'capi_ini::I-eve', 'capi_any::B-nat', 'capi_any::I-art', 'capi_any::I-geo', 'capi_any::B-eve', 'id:capitals::O', 'id:capitalize::O', 'id:decapitated::O', 'capi_any::I-eve', 'id:capitalist::O', 'id:capital-intensive::O', 'id:landscaping::O', 'id:per-capita::O', 'id:capitalization::O', 'id:capitalized::O', 'id:escaping::O', 'capi_any::I-gpe', 'id:capitalism::O', 'capi_any::I-nat', 'id:anti-capitalist::O', 'id:capitol::O']

1. point
['inside_point::O', 'inside_point::B-g

In [30]:
sp_added = spc.StructuredPerceptron(corpus_word_dict, corpus_tag_dict, added_feature_mapper)
sp_added.num_epochs = 5

In [31]:
sp_added.get_num_states(), sp_added.get_num_observations()

(17, 31979)

In [32]:
%%time
num_epochs = 15
sp_added.fit(added_feature_mapper.dataset, num_epochs)

Epoch: 0 Accuracy: 0.932321
Epoch: 1 Accuracy: 0.946742
Epoch: 2 Accuracy: 0.950434
Epoch: 3 Accuracy: 0.953119
Epoch: 4 Accuracy: 0.955183
Epoch: 5 Accuracy: 0.956330
Epoch: 6 Accuracy: 0.957800
Epoch: 7 Accuracy: 0.958352
Epoch: 8 Accuracy: 0.959670
Epoch: 9 Accuracy: 0.960568
Epoch: 10 Accuracy: 0.960595
Epoch: 11 Accuracy: 0.961291
Epoch: 12 Accuracy: 0.961944
Epoch: 13 Accuracy: 0.962345
Epoch: 14 Accuracy: 0.962734
CPU times: user 30min 43s, sys: 6.49 s, total: 30min 49s
Wall time: 30min 46s


In [33]:
# Model saving

sp_added.save_model("fitted_models/02_Added_Features")

In [35]:
# Model loading
sp_added = spc.StructuredPerceptron(corpus_word_dict, corpus_tag_dict, added_feature_mapper)
sp_added.load_model(dir="fitted_models/02_Added_Features")
sp_added.parameters

array([ 20.066667,  11.533333, -17.6     , ..., -11.933333,   0.733333,
         0.      ])